/**
 * "Similar course" logic for study pools.
 *
 * Two signals, combined:
 *
 * 1. Equivalence groups — sets of alternative tracks that cover the same
 *    material (MATH 2220 / 2250 / 2260 are all linear algebra). Nobody takes
 *    two of these, so co-enrollment data can never link them; they have to be
 *    declared, or imported from CourseTable's cross-listing ids.
 *
 * 2. Co-enrollment — the "students who took this class also took…" signal.
 *
 * Both come from `lib/data/courseGraph.json`, which is generated by
 * `npm run import:coursetable` and carries its own provenance. Nothing here
 * calls a language model.
 *
 * Course numbers are Yale College's four-digit catalog codes (S&DS 2380, not
 * 238). See README for how to import real data.
 */
import { COURSE_GRAPH, courseTitle, GRAPH_PROVENANCE } from "@/lib/courseGraph";

export type SimilarityReason = "equivalent" | "also-took" | "similar-title";

export type SimilarCourse = {
  courseCode: string;
  reason: SimilarityReason;
  /** 1 for equivalents; co-enrollment share (0..1) for "also took". */
  weight: number;
  /** Short human explanation shown as a chip. */
  label: string;
};

/**
 * Dept letters, optional & (S&DS), then a 4-digit number. 3-digit is only a
 * fallback so an old .ics still round-trips; canonical form is 4 digits.
 */
const COURSE_CODE_FOUR = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{4}[A-Z]?)/i;
const COURSE_CODE_THREE = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{3}[A-Z]?)/i;

export const CANONICAL_COURSE_CODE_RE =
  /^[A-Z]{1,4}(?:&[A-Z]{1,4})? \d{4}[A-Z]?$/;

function prep(input: string): string {
  return input.toUpperCase().replace(/&AMP;/g, "&");
}

function formatCode(dept: string, num: string): string {
  return `${dept.toUpperCase()} ${num.toUpperCase()}`;
}

/** Pull "S&DS 2380" out of a SUMMARY, syllabus line, etc. */
export function extractCourseCode(input: string): string {
  const text = prep(input);
  const four = text.match(COURSE_CODE_FOUR);
  if (four) return formatCode(four[1], four[2]);
  const three = text.match(COURSE_CODE_THREE);
  if (three) return formatCode(three[1], three[2]);
  return "UNKNOWN";
}

export function normalizeCourseCode(input: string): string {
  const extracted = extractCourseCode(input);
  return extracted === "UNKNOWN" ? input.trim().toUpperCase() : extracted;
}

export function isCanonicalCourseCode(input: string): boolean {
  return CANONICAL_COURSE_CODE_RE.test(normalizeCourseCode(input));
}

/** Alternative tracks for the same material. Four-digit Yale College codes. */
export const EQUIVALENCE_GROUPS = COURSE_GRAPH.equivalence;

/**
 * For each course, courses its students also took, as a share (0..1).
 * Reverse lookups are derived, so an import only needs one direction.
 */
export const CO_ENROLLMENT: Record<string, Record<string, number>> =
  COURSE_GRAPH.coEnrollment;

export function equivalentCourses(courseCode: string): { topic: string; courses: string[] } | null {
  const code = normalizeCourseCode(courseCode);
  const group = EQUIVALENCE_GROUPS.find((g) => g.courses.includes(code));
  if (!group) return null;
  return { topic: group.topic, courses: group.courses.filter((c) => c !== code) };
}

export function alsoTookCourses(courseCode: string): { courseCode: string; share: number }[] {
  const code = normalizeCourseCode(courseCode);
  const direct = CO_ENROLLMENT[code] ?? {};
  const merged = new Map<string, number>(Object.entries(direct));
  // Reverse edges: if Y's students also took X, X's students plausibly overlap Y.
  for (const [other, links] of Object.entries(CO_ENROLLMENT)) {
    if (other === code) continue;
    const share = links[code];
    if (typeof share === "number" && !merged.has(other)) merged.set(other, share * 0.8);
  }
  return Array.from(merged.entries())
    .map(([courseCode, share]) => ({ courseCode, share }))
    .sort((a, b) => b.share - a.share);
}

// ---- Lexical similarity over catalog titles ------------------------------
//
// Third signal: two courses whose titles say the same thing ("Introductory
// Microeconomics" / "Intro Micro: Policy Applications") are close even when
// the graph has no edge. Tokens are stemmed crudely and matched by prefix so
// "micro" hits "microeconomics".

const TITLE_STOPWORDS = new Set([
  "the", "of", "and", "to", "in", "a", "an", "for", "on", "with", "from", "at",
  "i", "ii", "iii", "iv", "v", "its", "into", "through", "via", "or", "by",
  "seminar", "topics", "special", "selected", "readings", "tutorial", "lab",
  "laboratory", "section", "independent", "directed", "senior", "junior",
  "first-year", "freshman", "workshop", "practicum", "colloquium", "studies",
  "study", "course", "courses",
]);

function titleTokens(title: string): string[] {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length >= 3 && !TITLE_STOPWORDS.has(t))
    .map((t) => t.replace(/(ical|ics|ies|ing|ed|s)$/, (m) => (t.length - m.length >= 4 ? "" : m)));
}

function tokenMatch(a: string, b: string): boolean {
  if (a === b) return true;
  const short = a.length < b.length ? a : b;
  const long = a.length < b.length ? b : a;
  return short.length >= 5 && long.startsWith(short);
}

/** 0..1 overlap of meaningful title words. */
export function titleSimilarity(a: string, b: string): number {
  const ta = titleTokens(a);
  const tb = titleTokens(b);
  if (ta.length === 0 || tb.length === 0) return 0;
  let hits = 0;
  const used = new Set<number>();
  for (const x of ta) {
    const j = tb.findIndex((y, idx) => !used.has(idx) && tokenMatch(x, y));
    if (j >= 0) {
      used.add(j);
      hits += 1;
    }
  }
  return hits / Math.max(ta.length, tb.length);
}

const TITLE_MIN_SCORE = 0.5;

/** Courses whose catalog title reads like this one's. */
export function similarTitleCourses(
  courseCode: string,
  limit = 4,
): { courseCode: string; title: string; score: number }[] {
  const code = normalizeCourseCode(courseCode);
  const mine = courseTitle(code);
  if (!mine) return [];
  const out: { courseCode: string; title: string; score: number }[] = [];
  for (const [other, title] of Object.entries(COURSE_GRAPH.titles)) {
    if (other === code || !title) continue;
    const score = titleSimilarity(mine, title);
    if (score >= TITLE_MIN_SCORE) out.push({ courseCode: other, title, score });
  }
  return out.sort((a, b) => b.score - a.score || a.courseCode.localeCompare(b.courseCode)).slice(0, limit);
}

/**
 * Equivalents first, then co-enrollment by share, then lexical title matches.
 * Never includes the course itself.
 */
export function similarCourses(courseCode: string, limit = 6): SimilarCourse[] {
  const code = normalizeCourseCode(courseCode);
  const out: SimilarCourse[] = [];
  const seen = new Set<string>([code]);

  const eq = equivalentCourses(code);
  if (eq) {
    for (const c of eq.courses) {
      seen.add(c);
      out.push({
        courseCode: c,
        reason: "equivalent",
        weight: 1,
        label: `Same material: ${eq.topic.toLowerCase()}`,
      });
    }
  }

  const titleMatches = similarTitleCourses(code, 3).filter((t) => !seen.has(t.courseCode));
  // Leave room for a couple of title matches even when the graph is dense.
  const alsoTookCap = Math.max(1, limit - Math.min(2, titleMatches.length));
  for (const { courseCode: c, share } of alsoTookCourses(code)) {
    if (out.length >= alsoTookCap) break;
    if (seen.has(c)) continue;
    seen.add(c);
    out.push({
      courseCode: c,
      reason: "also-took",
      weight: share,
      label: alsoTookLabel(code, share),
    });
  }

  for (const t of titleMatches) {
    if (seen.has(t.courseCode)) continue;
    seen.add(t.courseCode);
    out.push({
      courseCode: t.courseCode,
      reason: "similar-title",
      weight: t.score * 0.9,
      label: `Similar title: “${t.title}”`,
    });
  }

  return out.slice(0, limit);
}

/**
 * Phrase an edge according to what the numbers actually are.
 *
 * A counted co-enrollment export supports "46% of students also took this".
 * A catalog-derived graph does not — it only knows two courses look adjacent —
 * so it must not borrow the language of a statistic it never measured.
 */
function alsoTookLabel(courseCode: string, share: number): string {
  const percent = Math.round(share * 100);
  switch (GRAPH_PROVENANCE.kind) {
    case "coursetable-coenrollment":
      return `${percent}% of ${courseCode} students also took this`;
    case "coursetable-catalog":
      return `Close to ${courseCode} in the catalog`;
    default:
      return `${percent}% overlap in the demo sample`;
  }
}
