/**
 * "Similar course" logic for study pools.
 *
 * Same-class pooling is first-class. "Similar" chips are courses whose
 * CourseTable catalog descriptions overlap (token / TF-IDF cosine), plus
 * cross-listings from `same_course_id`. This is not co-enrollment and not
 * "adjacent subject."
 *
 * Numbers come from `lib/data/courseGraph.json`, generated by
 * `npm run import:coursetable`. Nothing here calls a language model.
 */
import { COURSE_GRAPH, courseTitle, GRAPH_PROVENANCE } from "@/lib/courseGraph";

export type SimilarityReason = "equivalent" | "description" | "similar-title";

export type SimilarCourse = {
  courseCode: string;
  reason: SimilarityReason;
  /** 1 for equivalents; description-overlap score (0..1) otherwise. */
  weight: number;
  /** Short human explanation shown as a chip. */
  label: string;
};

/**
 * Dept letters, optional & (S&DS), then a 4-digit number. 3-digit is only a
 * fallback so an old .ics still round-trips; canonical form is 4 digits.
 */
const COURSE_CODE_FOUR = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{4}[A-Z]?)/i;
const COURSE_CODE_THREE = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{3}[A-Z]?)/i;

export const CANONICAL_COURSE_CODE_RE =
  /^[A-Z]{1,4}(?:&[A-Z]{1,4})? \d{4}[A-Z]?$/;

function prep(input: string): string {
  return input.toUpperCase().replace(/&AMP;/g, "&");
}

function formatCode(dept: string, num: string): string {
  return `${dept.toUpperCase()} ${num.toUpperCase()}`;
}

/** Pull "S&DS 2380" out of a SUMMARY, syllabus line, etc. */
export function extractCourseCode(input: string): string {
  const text = prep(input);
  const four = text.match(COURSE_CODE_FOUR);
  if (four) return formatCode(four[1], four[2]);
  const three = text.match(COURSE_CODE_THREE);
  if (three) return formatCode(three[1], three[2]);
  return "UNKNOWN";
}

export function normalizeCourseCode(input: string): string {
  const extracted = extractCourseCode(input);
  return extracted === "UNKNOWN" ? input.trim().toUpperCase() : extracted;
}

export function isCanonicalCourseCode(input: string): boolean {
  return CANONICAL_COURSE_CODE_RE.test(normalizeCourseCode(input));
}

/** Cross-listed CourseTable listings for the same material. */
export const EQUIVALENCE_GROUPS = COURSE_GRAPH.equivalence;

export const DESCRIPTION_SIMILARITY: Record<string, Record<string, number>> =
  COURSE_GRAPH.descriptionSimilarity;

export function equivalentCourses(courseCode: string): { topic: string; courses: string[] } | null {
  const code = normalizeCourseCode(courseCode);
  const group = EQUIVALENCE_GROUPS.find((g) => g.courses.includes(code));
  if (!group) return null;
  return { topic: group.topic, courses: group.courses.filter((c) => c !== code) };
}

export function descriptionSimilarCourses(
  courseCode: string,
): { courseCode: string; score: number }[] {
  const code = normalizeCourseCode(courseCode);
  const direct = DESCRIPTION_SIMILARITY[code] ?? {};
  const merged = new Map<string, number>(Object.entries(direct));
  for (const [other, links] of Object.entries(DESCRIPTION_SIMILARITY)) {
    if (other === code) continue;
    const score = links[code];
    if (typeof score === "number" && !merged.has(other)) merged.set(other, score);
  }
  return Array.from(merged.entries())
    .map(([courseCode, score]) => ({ courseCode, score }))
    .sort((a, b) => b.score - a.score);
}

// ---- Title similarity (fallback when the description graph has no edge) ----

const TITLE_STOPWORDS = new Set([
  "the", "of", "and", "to", "in", "a", "an", "for", "on", "with", "from", "at",
  "i", "ii", "iii", "iv", "v", "its", "into", "through", "via", "or", "by",
  "seminar", "topics", "special", "selected", "readings", "tutorial", "lab",
  "laboratory", "section", "independent", "directed", "senior", "junior",
  "first-year", "freshman", "workshop", "practicum", "colloquium", "studies",
  "study", "course", "courses",
]);

function titleTokens(title: string): string[] {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length >= 3 && !TITLE_STOPWORDS.has(t))
    .map((t) => t.replace(/(ical|ics|ies|ing|ed|s)$/, (m) => (t.length - m.length >= 4 ? "" : m)));
}

function tokenMatch(a: string, b: string): boolean {
  if (a === b) return true;
  const short = a.length < b.length ? a : b;
  const long = a.length < b.length ? b : a;
  return short.length >= 5 && long.startsWith(short);
}

/** 0..1 overlap of meaningful title words ("Intro Micro" vs "Introductory Microeconomics"). */
export function titleSimilarity(a: string, b: string): number {
  const ta = titleTokens(a);
  const tb = titleTokens(b);
  if (ta.length === 0 || tb.length === 0) return 0;
  let hits = 0;
  const used = new Set<number>();
  for (const x of ta) {
    const j = tb.findIndex((y, idx) => !used.has(idx) && tokenMatch(x, y));
    if (j >= 0) {
      used.add(j);
      hits += 1;
    }
  }
  return hits / Math.max(ta.length, tb.length);
}

const TITLE_MIN_SCORE = 0.5;

/** Courses whose catalog title reads like this one's. */
export function similarTitleCourses(
  courseCode: string,
  limit = 4,
): { courseCode: string; title: string; score: number }[] {
  const code = normalizeCourseCode(courseCode);
  const mine = courseTitle(code);
  if (!mine) return [];
  const out: { courseCode: string; title: string; score: number }[] = [];
  for (const [other, title] of Object.entries(COURSE_GRAPH.titles)) {
    if (other === code || !title) continue;
    const score = titleSimilarity(mine, title);
    if (score >= TITLE_MIN_SCORE) out.push({ courseCode: other, title, score });
  }
  return out
    .sort((a, b) => b.score - a.score || a.courseCode.localeCompare(b.courseCode))
    .slice(0, limit);
}

/**
 * Equivalents first, then catalog-description overlap, then title matches
 * for anything the description graph missed. Never includes the course itself.
 */
export function similarCourses(courseCode: string, limit = 6): SimilarCourse[] {
  const code = normalizeCourseCode(courseCode);
  const out: SimilarCourse[] = [];
  const seen = new Set<string>([code]);

  const eq = equivalentCourses(code);
  if (eq) {
    for (const c of eq.courses) {
      seen.add(c);
      out.push({
        courseCode: c,
        reason: "equivalent",
        weight: 1,
        label: `Same CourseTable listing: ${eq.topic}`,
      });
    }
  }

  const titleMatches = similarTitleCourses(code, 3).filter((t) => !seen.has(t.courseCode));
  const descriptionCap = Math.max(1, limit - Math.min(2, titleMatches.length));
  for (const { courseCode: c, score } of descriptionSimilarCourses(code)) {
    if (out.length >= descriptionCap) break;
    if (seen.has(c)) continue;
    seen.add(c);
    out.push({
      courseCode: c,
      reason: "description",
      weight: score,
      label: descriptionLabel(score),
    });
  }

  for (const t of titleMatches) {
    if (seen.has(t.courseCode)) continue;
    seen.add(t.courseCode);
    out.push({
      courseCode: t.courseCode,
      reason: "similar-title",
      weight: t.score * 0.9,
      label: `Similar title: “${t.title}”`,
    });
  }

  return out.slice(0, limit);
}

function descriptionLabel(score: number): string {
  const percent = Math.round(score * 100);
  if (GRAPH_PROVENANCE.kind === "coursetable-descriptions") {
    return `Catalog description similarity (${percent}%)`;
  }
  return `Catalog description similarity (${percent}%)`;
}
