/**
 * "Similar course" logic for study pools.
 *
 * Same-class pooling is first-class. "Similar" chips are courses whose
 * CourseTable catalog descriptions overlap (token / TF-IDF cosine), plus
 * cross-listings from `same_course_id`. This is not co-enrollment and not
 * "adjacent subject."
 *
 * Numbers come from `lib/data/courseGraph.json`, generated by
 * `npm run import:coursetable`. Nothing here calls a language model.
 */
import { COURSE_GRAPH, GRAPH_PROVENANCE } from "@/lib/courseGraph";

export type SimilarityReason = "equivalent" | "description";

export type SimilarCourse = {
  courseCode: string;
  reason: SimilarityReason;
  /** 1 for equivalents; description-overlap score (0..1) otherwise. */
  weight: number;
  /** Short human explanation shown as a chip. */
  label: string;
};

/**
 * Dept letters, optional & (S&DS), then a 4-digit number. 3-digit is only a
 * fallback so an old .ics still round-trips; canonical form is 4 digits.
 */
const COURSE_CODE_FOUR = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{4}[A-Z]?)/i;
const COURSE_CODE_THREE = /([A-Z]{1,4}(?:&[A-Z]{1,4})?)\s*-?\s*(\d{3}[A-Z]?)/i;

export const CANONICAL_COURSE_CODE_RE =
  /^[A-Z]{1,4}(?:&[A-Z]{1,4})? \d{4}[A-Z]?$/;

function prep(input: string): string {
  return input.toUpperCase().replace(/&AMP;/g, "&");
}

function formatCode(dept: string, num: string): string {
  return `${dept.toUpperCase()} ${num.toUpperCase()}`;
}

/** Pull "S&DS 2380" out of a SUMMARY, syllabus line, etc. */
export function extractCourseCode(input: string): string {
  const text = prep(input);
  const four = text.match(COURSE_CODE_FOUR);
  if (four) return formatCode(four[1], four[2]);
  const three = text.match(COURSE_CODE_THREE);
  if (three) return formatCode(three[1], three[2]);
  return "UNKNOWN";
}

export function normalizeCourseCode(input: string): string {
  const extracted = extractCourseCode(input);
  return extracted === "UNKNOWN" ? input.trim().toUpperCase() : extracted;
}

export function isCanonicalCourseCode(input: string): boolean {
  return CANONICAL_COURSE_CODE_RE.test(normalizeCourseCode(input));
}

/** Cross-listed CourseTable listings for the same material. */
export const EQUIVALENCE_GROUPS = COURSE_GRAPH.equivalence;

export const DESCRIPTION_SIMILARITY: Record<string, Record<string, number>> =
  COURSE_GRAPH.descriptionSimilarity;

export function equivalentCourses(courseCode: string): { topic: string; courses: string[] } | null {
  const code = normalizeCourseCode(courseCode);
  const group = EQUIVALENCE_GROUPS.find((g) => g.courses.includes(code));
  if (!group) return null;
  return { topic: group.topic, courses: group.courses.filter((c) => c !== code) };
}

export function descriptionSimilarCourses(
  courseCode: string,
): { courseCode: string; score: number }[] {
  const code = normalizeCourseCode(courseCode);
  const direct = DESCRIPTION_SIMILARITY[code] ?? {};
  const merged = new Map<string, number>(Object.entries(direct));
  for (const [other, links] of Object.entries(DESCRIPTION_SIMILARITY)) {
    if (other === code) continue;
    const score = links[code];
    if (typeof score === "number" && !merged.has(other)) merged.set(other, score);
  }
  return Array.from(merged.entries())
    .map(([courseCode, score]) => ({ courseCode, score }))
    .sort((a, b) => b.score - a.score);
}

/** Equivalents first, then catalog-description overlap. Never includes the course itself. */
export function similarCourses(courseCode: string, limit = 6): SimilarCourse[] {
  const code = normalizeCourseCode(courseCode);
  const out: SimilarCourse[] = [];
  const seen = new Set<string>([code]);

  const eq = equivalentCourses(code);
  if (eq) {
    for (const c of eq.courses) {
      seen.add(c);
      out.push({
        courseCode: c,
        reason: "equivalent",
        weight: 1,
        label: `Same CourseTable listing: ${eq.topic}`,
      });
    }
  }

  for (const { courseCode: c, score } of descriptionSimilarCourses(code)) {
    if (seen.has(c)) continue;
    seen.add(c);
    out.push({
      courseCode: c,
      reason: "description",
      weight: score,
      label: descriptionLabel(score),
    });
  }

  return out.slice(0, limit);
}

function descriptionLabel(score: number): string {
  const percent = Math.round(score * 100);
  if (GRAPH_PROVENANCE.kind === "coursetable-descriptions") {
    return `Catalog description similarity (${percent}%)`;
  }
  return `Catalog description similarity (${percent}%)`;
}
