import coffeeSnapshot from "@/lib/data/coffeeShops.json";
import libcalSnapshot from "@/lib/data/libcalSpaces.json";
import walkInSnapshot from "@/lib/data/walkInSpaces.json";
import { courseTablePointForSpot } from "@/lib/geo";
import type { StudyRecommendation } from "@/lib/types";

/**
 * Study spots the app knows about.
 *
 * Reservable rooms come from `lib/data/libcalSpaces.json`, generated by
 * `npm run import:libcal` from public schedule.yale.edu listings. Walk-in
 * reading rooms and open floors come from `lib/data/walkInSpaces.json`
 * (Yale Library's "Places to Study" page). Coffee shops come from
 * `lib/data/coffeeShops.json` with published street addresses.
 *
 * `capacity` is stored only when Yale published a number. Unknown is unknown.
 * Coordinates are building-level (rooms) or address geocodes (cafes), not a
 * surveyed chair.
 */
export type CapacitySource = "schedule.yale.edu" | "unknown";
export type CoordSource = "building" | "address" | "coursetable";

export type StudySpot = StudyRecommendation & {
  /** Stable slug, used in URLs and as the booking key. */
  id: string;
  capacity?: number;
  capacitySource: CapacitySource;
  coordSource?: CoordSource;
  /** Springshare LibCal space id behind schedule.yale.edu/space/<id>. */
  libcalSpaceId?: number;
  /** Room label exactly as LibCal prints it, e.g. "Bass C10F". */
  libcalLabel?: string;
  /** LibCal location id (`lid`) on schedule.yale.edu. */
  libcalLid?: number;
  /** LibCal group id (`gid`) on schedule.yale.edu. */
  libcalGid?: number;
  /** LibCal location name, e.g. "Bass Library". */
  locationName?: string;
  /** Human-readable opening hours, when known. */
  hours?: string;
};

type LibcalSpaceRow = {
  id: string;
  kind: "coffee" | "room";
  name: string;
  address: string;
  lat: number;
  lng: number;
  coordSource?: CoordSource;
  bookingUrl: string;
  libcalSpaceId: number;
  libcalLabel: string;
  libcalLid: number;
  libcalGid: number;
  locationName?: string;
  capacity?: number;
  capacitySource: CapacitySource;
  description?: string;
  tags?: string[];
};

type WalkInRow = {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  coordSource?: CoordSource;
  hours?: string;
  description?: string;
  tags?: string[];
};

type CoffeeRow = {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  coordSource?: CoordSource;
  hours?: string;
  description?: string;
  tags?: string[];
};

/** Catalog walk times stay 0 until the recommender has a real origin. */
function withUnknownWalk(
  spot: Omit<StudySpot, "walkingMinutes"> & { lat: number; lng: number },
): StudySpot {
  return {
    ...spot,
    walkingMinutes: 0,
  };
}

/** Prefer CourseTable's building pin when the spot's building is in that table. */
function withCourseTablePoint<T extends { name: string; address?: string; lat: number; lng: number; locationName?: string; coordSource?: CoordSource }>(
  spot: T,
): T {
  const point = courseTablePointForSpot(spot.locationName, spot.address, spot.name);
  if (!point) return spot;
  return { ...spot, lat: point.lat, lng: point.lng, coordSource: "coursetable" };
}

function fromLibcal(row: LibcalSpaceRow): StudySpot {
  return withUnknownWalk(
    withCourseTablePoint({
      id: row.id,
      kind: row.kind,
      name: row.name,
      address: row.address,
      lat: row.lat,
      lng: row.lng,
      locationName: row.locationName,
      coordSource: row.coordSource ?? "building",
      bookingUrl: row.bookingUrl,
      libcalSpaceId: row.libcalSpaceId,
      libcalLabel: row.libcalLabel,
      libcalLid: row.libcalLid,
      libcalGid: row.libcalGid,
      capacity: row.capacity,
      capacitySource: row.capacitySource,
      description: row.description,
      tags: row.tags,
    }),
  );
}

function fromWalkIn(row: WalkInRow): StudySpot {
  return withUnknownWalk(
    withCourseTablePoint({
      id: row.id,
      kind: "room",
      name: row.name,
      address: row.address,
      lat: row.lat,
      lng: row.lng,
      coordSource: row.coordSource ?? "building",
      capacitySource: "unknown",
      hours: row.hours,
      description: row.description,
      tags: row.tags,
    }),
  );
}

function fromCoffee(row: CoffeeRow): StudySpot {
  return withUnknownWalk({
    id: row.id,
    kind: "coffee",
    name: row.name,
    address: row.address,
    lat: row.lat,
    lng: row.lng,
    coordSource: row.coordSource ?? "address",
    capacitySource: "unknown",
    hours: row.hours,
    description: row.description,
    tags: row.tags,
  });
}

export const STUDY_SPOTS: StudySpot[] = [
  ...(libcalSnapshot.spaces as LibcalSpaceRow[]).map(fromLibcal),
  ...(walkInSnapshot.spaces as WalkInRow[]).map(fromWalkIn),
  ...(coffeeSnapshot.shops as CoffeeRow[]).map(fromCoffee),
];

export function findSpot(nameOrId: string): StudySpot | undefined {
  const needle = nameOrId.trim().toLowerCase();
  if (!needle) return undefined;
  return STUDY_SPOTS.find(
    (s) =>
      s.id === needle ||
      s.name.toLowerCase() === needle ||
      s.libcalLabel?.toLowerCase() === needle,
  );
}

/** Hard ceiling for a pool when capacity is unknown or a hall lists dozens of seats. */
export const UNKNOWN_SPOT_MAX_CAPACITY = 8;

export type CapacityRuling = {
  capacity: number;
  /** Set when the request was reduced, for the UI to explain. */
  note?: string;
};

/**
 * Decide how many seats a booking may open.
 *
 * A published Yale capacity wins as a hard cap. Pools never exceed
 * `UNKNOWN_SPOT_MAX_CAPACITY` even in a 30-seat classroom — that is a product
 * limit for a discussion group, not an invented room size. Unknown capacity
 * does not guess a number.
 */
export function resolveBookingCapacity(
  spotName: string,
  requested: number,
): CapacityRuling {
  const wanted = Number.isFinite(requested) ? Math.floor(requested) : 1;
  const spot = findSpot(spotName);
  const published =
    spot?.capacitySource === "schedule.yale.edu" && typeof spot.capacity === "number"
      ? spot.capacity
      : undefined;
  const hardCap =
    published !== undefined
      ? Math.min(published, UNKNOWN_SPOT_MAX_CAPACITY)
      : UNKNOWN_SPOT_MAX_CAPACITY;
  const capacity = Math.min(Math.max(1, wanted), hardCap);

  if (capacity === wanted && published === undefined) {
    return { capacity };
  }
  if (capacity === wanted && published !== undefined && published <= UNKNOWN_SPOT_MAX_CAPACITY) {
    return { capacity };
  }
  if (published !== undefined && published > UNKNOWN_SPOT_MAX_CAPACITY && capacity !== wanted) {
    return {
      capacity,
      note: `${spot?.name ?? spotName} lists ${published} seats on schedule.yale.edu; the pool caps at ${capacity} so it stays a small study group.`,
    };
  }
  if (published !== undefined && capacity !== wanted) {
    return {
      capacity,
      note: `${spot?.name ?? spotName} seats ${published} on schedule.yale.edu, so the pool caps at ${capacity}.`,
    };
  }
  if (capacity !== wanted) {
    return {
      capacity,
      note: `Seat count is not published for this spot; the pool caps at ${capacity}.`,
    };
  }
  return { capacity };
}
